### ISSUE TITLE
BUG mapping to other node creates visual additional node

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#37]
When mapping an existing edge to an existing node, it appears that the old empty node still exists:

![image](https://cloud.githubusercontent.com/assets/5627431/22427701/719e6aac-e704-11e6-875b-e9a559752af5.png)

![image](https://cloud.githubusercontent.com/assets/5627431/22427709/79439b2e-e704-11e6-95d0-eb7a0f93a953.png)

**Comment by mzeinstra** [comment]
And after an safe it empty the node it maps to:

![image](https://cloud.githubusercontent.com/assets/5627431/22427767/aabec12e-e704-11e6-8ba6-15cff939c34a.png)

**Comment by arnaud-brun** [comment]
Mapping to an existing node doen't create extra edges, nor extra nodes anymore.
Fix : remove all out edges of the current node, to better redraw them afterwards
         and monitor orphan nodes, to delete them if necessary.
