### ISSUE TITLE
Orphan nodes are presented as new root nodes

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#39]
![image](https://cloud.githubusercontent.com/assets/5627431/22506149/2636bd68-e87f-11e6-80be-5aace71ca923.png)

See: Test Audiovisual Data

**Comment by arnaud-brun** [comment]
This problem should be now avoid by design.
In case of problem, all nodes can be deleting if they're not the root node, nor a block content box (the rectangle regrouping the block node and its direct question children)
