### ISSUE TITLE
Error provided adding a numeric question, but no indication given how to solve the error.

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#41]
![image](https://cloud.githubusercontent.com/assets/5627431/22507377/9fa21804-e885-11e6-8ea2-32f8bad93764.png)

**Comment by arnaud-brun** [comment]
Prevent user to inject a question mark ('?')  in the user input short name
Reason : breaks the regex used to check if inputs expression is correct
Prevision : remove all special characters not recognized inside the regex

**Comment by arnaud-brun** [comment]
Allow user to use any kind of characters except - and + signs, necessary for computation
