### ISSUE TITLE
For numerical questions only show the input question

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#42]
The the case below the question 'Was the work made before 2003' is not necessary. We only use it in the back end to recognise the question. 

![image](https://cloud.githubusercontent.com/assets/5627431/22514619/32224752-e8a0-11e6-9973-2aee06288fb2.png)

**Comment by arnaud-brun** [comment]
The question is not displayed anymore, despite the actual structure is kept
Actual structure 
div questionId > {div userInput1 > label | br | input} || {div userInput2 > label | br | input} <
