### ISSUE TITLE
Point the end of one node to an existing node resets the existing node

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#44]
Here I added a new edge to an existing node. I saved, reloaded the page and now the node with two lines going into them seem to have reset.

![image](https://cloud.githubusercontent.com/assets/5627431/22515348/735196e0-e8a2-11e6-9fc0-9bca2f8cb1e0.png)

**Comment by mzeinstra** [comment]
Could not reproduce with a question, above example was with a result

**Comment by arnaud-brun** [comment]
Targeting a result from an other node doesn't reset the content of the result node anymore
