### ISSUE TITLE
identifier dropdown needs to be as wide as possible

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#46]
This becomes very difficult to read, and this presents only 1/4 of the questions in a normal process.

![image](https://cloud.githubusercontent.com/assets/5627431/22543192/e526b4b6-e92f-11e6-9e6e-81ef0db8469b.png)

**Comment by mzeinstra** [comment]
Dropdown also needs a scroll to get to the lower questions

**Comment by arnaud-brun** [comment]
Column type inserted before the question column
Autocomplete dropdown wider with scrollbar
