### ISSUE TITLE
Clicking on data in a made flowchart visually removes the data in the left list

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#47]
Steps to reproduce

Go to Test -> Audiovisual and let the data load.
Click on data in the top-left. 

![image](https://cloud.githubusercontent.com/assets/5627431/22543325/5c267b64-e930-11e6-95e2-76de0e75965f.png)

Data is not removed from the database, reloading the data works

**Comment by arnaud-brun** [comment]
Clicking on data doesn't have this kind of effect anymore
