### ISSUE TITLE
Disconnecting a node from a follow up node gives an error

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#48]
In the example below I needed to disconnect the block from the follow-up question, because I forgot a question. I went to the block node and clicked on target to 'New Node'. This gave an error.

![image](https://cloud.githubusercontent.com/assets/5627431/22543683/f8246d22-e931-11e6-8ee4-214181e6fab1.png)

**Comment by arnaud-brun** [comment]
A block, and other nodes can be disconnected from their child.
The child node will be deleted if it doesn't have any other predecessors
