### ISSUE TITLE
Links sometimes are not loaded to connect edges to existing nodes

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#58]
After adding a block question and an additional question I cannot connect an edge to a new node. I get these type of options.

![image](https://cloud.githubusercontent.com/assets/5627431/22890746/97ccbed6-f20d-11e6-86d9-6a6b59addc65.png)

Saving and reloading resolves this.

**Comment by mzeinstra** [comment]
Maybe it is a different bug but I get this

I want to connect the lower edge to the upper node.
![1](https://cloud.githubusercontent.com/assets/5627431/22925347/9efaa506-f2a8-11e6-97fb-626f26fc840b.png)

But I get

![2](https://cloud.githubusercontent.com/assets/5627431/22925362/b09ce404-f2a8-11e6-9c77-d4f304cd6f19.png)

Reloading helps and allows me to make the connection:

![3](https://cloud.githubusercontent.com/assets/5627431/22925403/e7889cd8-f2a8-11e6-88eb-888e641f2120.png)

**Comment by mzeinstra** [comment]
Similarly this happens

I want to connect the upper empty edge to the lower node:
![2-1](https://cloud.githubusercontent.com/assets/5627431/22926446/e39ae262-f2ac-11e6-87f0-f5440d45b003.png)
It shows no ids to the available nodes
![2-2](https://cloud.githubusercontent.com/assets/5627431/22926457/eda1ed3c-f2ac-11e6-8bd5-9cd5fa37fd64.png)
However after savind and reloading it does show the ids of the nodes
![2-3](https://cloud.githubusercontent.com/assets/5627431/22926477/000681ae-f2ad-11e6-837c-423d0c2cc81b.png)
And makes the right connection
![2-4](https://cloud.githubusercontent.com/assets/5627431/22926487/0c005aa2-f2ad-11e6-93d2-c95f7b80f01f.png)

**Comment by arnaud-brun** [comment]
I've investigated in with your set of data.
I can't figure out how to regenerate those bugs.

Can you, if it reappears, try to close the node configuration modal and reopen it ?
I suspect this is a timing issue on a data injection in JavaScript, but it's quite hard to detect as this bugs seems to appears from times to times...
