### ISSUE TITLE
API does not work

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#59]
![screen shot 2017-02-14 at 21 40 40](https://cloud.githubusercontent.com/assets/5627431/22948343/602ea2f4-f2fe-11e6-9739-bbc3b3f46e52.png)

**Comment by arnaud-brun** [comment]
Apache configuration fixed
The the proxy pass for the '/api' route wasn't redirected to the publicly exposed server (dev.outofcopyright.eu). It was instead exposed on localhost....

Configuration file of the wordpress updated and associated readme too
