### ISSUE TITLE
Cannot remove questions

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#60]
I tried removing a duplicate question but nothing happened after I clicked delete
![image](https://cloud.githubusercontent.com/assets/5627431/23258486/c62d52f0-f9c8-11e6-8041-3a96f56c2e89.png)

**Comment by arnaud-brun** [comment]
Problem due to a concurrency issue in JavaScript callback, causing the lost of the database id on which we had to work on.

A check is applied when the data is retrieved, so that modifications can be applied in order to save the database id.

This should be fixed now
