### ISSUE TITLE
adding an answer triggers immediate warning popup, even on first attempt

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#62]
I can reproduce this in Firefox.

![bug](https://cloud.githubusercontent.com/assets/5627431/23696121/9babec70-03e2-11e7-958e-e0f8be4f90af.gif)

**Comment by arnaud-brun** [comment]
Select tag behavior patched so that :
empty response -> not empty response : warning modal is not shown
not empty response -> other response (even empty) : warning modal is displayed
