### ISSUE TITLE
Flowchart corrupted – need advice to repair

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#66]
I have no steps to reproduce, other than I did a delete somewhere during my process of creating this.

The flowchart (France - Phonogram) now has 3 roots:

![image](https://cloud.githubusercontent.com/assets/5627431/25180182/52ef40f8-250d-11e7-8a3d-0e25e49fb8ad.png)

And the final node refers upwards when creating a new and cannot be redirected to a empty node:

![image](https://cloud.githubusercontent.com/assets/5627431/25180232/7a45fcaa-250d-11e7-9573-4af62e0f3bb0.png)

where the node that the lower node is pointing to see seems empty but according to its parent is actually filled in:

![image](https://cloud.githubusercontent.com/assets/5627431/25180314/cbac1296-250d-11e7-9c36-c7e58b1e7acb.png)

Do I need to consider this as unrepairable en start this flowchart anew?

**Comment by mzeinstra** [comment]
The issues is unfortunately not solved with the latests patch (which I put on the server). 

See the following steps to reproduce (France Phonogram)
1. Notice the node 'Did you fill in any of the contact details of the composer(s) above?'
![image](https://cloud.githubusercontent.com/assets/5627431/25330965/c5f64538-28e1-11e7-89e6-9c3f93b845eb.png)
2. Notice the empty node at the end of the tree
![image](https://cloud.githubusercontent.com/assets/5627431/25330974/cbe1148c-28e1-11e7-8797-28718b941713.png)
3. Select the bottom-most question 'Did you fill in any of the contact details of the author(s) above?'
![image](https://cloud.githubusercontent.com/assets/5627431/25330988/d5146a18-28e1-11e7-8f68-1a007741914f.png)
4. Notice the problem. The node in (1) has no content and the end-node now points upwards to that node.
![image](https://cloud.githubusercontent.com/assets/5627431/25331016/e3fc1882-28e1-11e7-8fa8-37b5d18e53f4.png)

**Comment by arnaud-brun** [comment]
This bug has normally been fixed previously in commit 5f96e2c335c6d2629cd80337a7c784e6615ffbfb
