### ISSUE TITLE
Inputs are duplicated each time I save

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#67]
Pending resolution of the other problem with France Phonogram I started making France Audiovisual.

However it seems that everytime I save the User Inputs and Reference Values are duplicated:

![image](https://cloud.githubusercontent.com/assets/5627431/25331736/63209046-28e4-11e7-8876-51d006a6bf91.png)

**Comment by arnaud-brun** [comment]
This bug appends also when you choose a type of work again and again.

This bad behavior should be fixed now.
