### ISSUE TITLE
Saving without adding a first node removes the root

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#68]
In France Audiovisual I saved, and reloaded the screen. 

This caused the root node to dissappear, now I cannot start building this flowchart.

![image](https://cloud.githubusercontent.com/assets/5627431/25338923/2e7a26d2-2901-11e7-835c-c9807404d3a1.png)

I'll remove the flowchart in the dabatase to start anew, but I believe this needs have check build in somewhere.

**Comment by arnaud-brun** [comment]
In this situation, an empty graph was saved into the database.
If the graph is empty, a new root node is created ensuring there is always a node to work with.
