### ISSUE TITLE
Dropdown response time drops down

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#70]
With large decision processes some of the question selection boxes start running real slowly.

In the GIF below (UK->phonograms), two large decision trees have been finished (audiovisual works and written works) and the response time seems to slow down to about 8 seconds. I believe there is an inefficient loop or query working here that needs to process a lot before getting all questions from a tree.

![slow response](https://cloud.githubusercontent.com/assets/5627431/26633879/262ad37e-4615-11e7-9b2f-d5db524e46f4.gif)

What to do?

**Comment by mzeinstra** [comment]
It seems more like a memory leak, a cmd-shift-r resolved the issue. I will follow up if I have better steps to reproduce.

**Comment by arnaud-brun** [comment]
It was a multiple redefinition of the autocomplete widget. Only the sources of the widget is refreshed now
