### ISSUE TITLE
PDF print only does a screenshot

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#72]
Search reports are longer than a page, this won't fit.

![6flgexjz](https://user-images.githubusercontent.com/5627431/27285220-3d05bc44-54fc-11e7-837a-ac7cf3894f86.png)

**Comment by mzeinstra** [comment]
Also I see some encoding errors in the pdf version.

**Comment by arnaud-brun** [comment]
The CSS file on the server, used to generate the pdf, was using the property 'overflow'.
This property restrict the pdf generation to only what was displayed on screen.

The UTF-8 charset is now specified at the pdf generation.

**Comment by mzeinstra** [comment]
Thanks this solves most of the issues related to the PDF print. I did some further cosmetic changes in https://github.com/diligentsearch/diligentsearch-website/commit/53b0a0754055e419896063d9c53324cd38fc77d2

One issue remains. When the input exceed the boundaries of the input field the input is hidden. The entire field should be shown.

The solution I found for this would probably require a javascript intervention, as I found no pure css solutions. 

![problematic edit field printing](https://user-images.githubusercontent.com/5627431/27630502-f38cd100-5bf5-11e7-8821-9b17446d1573.png)

**Comment by arnaud-brun** [comment]
Cannot solve this problem easily on front end side.
Will try to replace input text elements with \<p> tags on server side with library cheerio. 
(https://github.com/cheeriojs/cheerio).

**Comment by arnaud-brun** [comment]
Solution previously described is set up.
Some css has been injected to display in proper way inject p tags, so that a large input looks like a real paragraph.

Restart of the server required, with injection of new dependency cheerio.

Injection of dependency:
`cd path/to/server/folder`
`npm install`

Restart of the server
`forever start server.js`
