### ISSUE TITLE
I may have corrupted Italy -> phonograms

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#74]
on diligentsearch.eu/editor/ I may have corrupted phonograms for Italy. 

I saw I forgot a question so I removed a branch. No empty node appeared in its place. I tried saving and reloading an now nothing appears anymore.

**Comment by arnaud-brun** [comment]
Data in phpmyadmin are patched so that the graphical creation can be resumed.
I will need more input to figure out how this bug has produces such effects on DB
