### ISSUE TITLE
Dropdowns to select question don't work properly anymore

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#75]
Below you see that dropdowns for block questions, show normal question.

![dropdowns don t work properly anymore](https://user-images.githubusercontent.com/5627431/27373784-e0571ed8-5669-11e7-85ec-5c7e6a97a7a9.png)

**Comment by mzeinstra** [comment]
Additional information. It is only the content of the first dropdown that persist, the attached screenshot also shows the JS errors (unsure if related).

![first set of section is loaded](https://user-images.githubusercontent.com/5627431/27377592-aefa232e-5675-11e7-9b7c-16ca4159cabf.png)

**Comment by mzeinstra** [comment]
I believe it is because it loads only the first time and doesn't empty when you select a different kind of category.

**Comment by arnaud-brun** [comment]
The dropdown source was updated after a change of the category but not the relative select handler, still triggering the old datasource.
