### ISSUE TITLE
Loading saved searches prompts change notification

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#77]
Upon loading a saved flowchart a change notifcation pops-up.

Steps to reproduce
Go to the calculator and load the latest version the search with this code 6HUWCEvN
You are presented with prompt that should not appear

![changing value upon load](https://user-images.githubusercontent.com/5627431/27627565-89fa8ca4-5bec-11e7-8479-52137d57ef10.png)

**Comment by arnaud-brun** [comment]
The select dropdown event listener was not able to make the distinction between a loading form and a user altered response
