### ISSUE TITLE
Saving an empty decision tree causes the empty node to dissappear upon reload

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#9]
![image](https://cloud.githubusercontent.com/assets/5627431/21990203/30af1768-dc0e-11e6-85ce-e35a5be6ce90.png)

**Comment by arnaud-brun** [comment]
This problem was due to a non empty result coming from database, it should be fixed now;
File : app/js/decision-tree.js
Line : 43
